# -*- coding: utf-8 -*-
"""ABA ASSIGNMENT updated

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RM6N9kCad4ehHWIcyXhBNtWjTf939QqA
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('/content/Customer_Data.xlsx')

df

df = df.drop('Customer_ID', axis=1)
df

# Check for missing values in each column
print(df.isnull().sum())

df.dtypes

# Convert 'Referral_Used' to boolean
df['Referral_Used'] = df['Referral_Used'].astype(bool)

for col in ['Gender', 'Marital_Status', 'Education_Level', 'Occupation', 'City', 'Region', 'Product_Purchased', 'Preferred_Channel']:
    try:
        df[col] = pd.to_numeric(df[col])
    except ValueError:
        # Handle non-numeric values by converting to category type
        df[col] = df[col].astype('category').cat.codes

print(df.describe())

# Value counts for categorical features
for col in df.select_dtypes(include=['object', 'bool']):
    print(f"\nValue counts for {col}:")
    print(df[col].value_counts())


# Distribution of numerical features (example using histograms)
df.hist(figsize=(10, 8))
plt.tight_layout()  # Adjust layout to prevent overlapping plots
plt.show()

variables = ['Gender', 'Age', 'Marital_Status', 'Income', 'Spending_Score']
correlation_matrix = df[variables].corr()
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Variables')
plt.show()

df.dtypes

import plotly.express as px
import plotly.graph_objects as go


# Interactive Scatter Plot: Spending Score vs. Income
fig = px.scatter(df, x='Income', y='Spending_Score', color='Age',
                 hover_data=['Gender', 'Marital_Status'], title='Spending Score vs. Income')
fig.show()


# Interactive Histogram: Distribution of Age
fig = px.histogram(df, x="Age", nbins=20, title="Distribution of Customer Age", color="Gender")
fig.show()

# Interactive Box Plot: Spending Score by Education Level
fig = px.box(df, x='Education_Level', y='Spending_Score', title="Spending Score by Education Level")
fig.show()


# Interactive Violin Plot: Income distribution by Product Purchased
fig = px.violin(df, y="Income", x="Product_Purchased", box=True, points="all",
          hover_data=df.columns)
fig.show()


# Correlation Heatmap (Interactive)
correlation_matrix = df.corr()
fig = go.Figure(data=go.Heatmap(z=correlation_matrix,
                                x=correlation_matrix.columns,
                                y=correlation_matrix.columns,
                                colorscale='Viridis'))
fig.update_layout(title='Correlation Matrix of Variables')
fig.show()

# Pair Plot (Interactive)
fig = px.scatter_matrix(df, dimensions=['Age', 'Income', 'Spending_Score', 'Monthly_Purchases'], color="Gender")
fig.show()

# Distribution of Numerical features (Interactive)
for col in df.select_dtypes(include=np.number):
  fig = px.histogram(df, x=col, nbins=20, title=f'Distribution of {col}')
  fig.show()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import statsmodels.api as sm

# Define features (X) and target variable (y)
X = df[['Income', 'Age', 'Education_Level', 'Monthly_Purchases']]  # Example features, you can modify
y = df['Spending_Score']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
print(f"R-squared: {r2}")
print(f"Mean Squared Error: {mse}")

# Statsmodels for detailed regression summary
X_train_sm = sm.add_constant(X_train)  # Add a constant (intercept)
model_sm = sm.OLS(y_train, X_train_sm).fit()
print(model_sm.summary())


import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import statsmodels.api as sm

# Set page config for aesthetics
st.set_page_config(page_title="Customer Spending Analysis", page_icon=":bar_chart:", layout="wide")

# Add a title and description
st.title("Customer Spending Score Prediction")
st.write("This app analyzes customer data and predicts their spending score using a linear regression model.")


# Load data (replace with your actual data loading)
try:
    df = pd.read_excel('/content/Customer_Data.xlsx')
    # ... [Your data preprocessing code from the original notebook] ...
except FileNotFoundError:
    st.error("Error: 'Customer_Data.xlsx' not found. Please upload the file.")
    st.stop()

# Display the dataframe (optional)
#st.dataframe(df)

# Sidebar for user input
st.sidebar.header("User Input")

# ... [Your sidebar inputs for model prediction (e.g., Income, Age, etc.)] ...
# Example:
income = st.sidebar.number_input("Income", min_value=0, value=50000)
age = st.sidebar.number_input("Age", min_value=18, max_value=100, value=30)
education_level = st.sidebar.number_input("Education Level", min_value=0, value=2)  # Adjust based on your encoding
monthly_purchases = st.sidebar.number_input("Monthly Purchases", min_value=0, value=50)

# Create a prediction button
if st.sidebar.button("Predict Spending Score"):
    # Prepare input data for prediction
    input_data = pd.DataFrame({
        'Income': [income],
        'Age': [age],
        'Education_Level': [education_level],
        'Monthly_Purchases': [monthly_purchases]
    })

    # Make the prediction
    prediction = model.predict(input_data)

    st.subheader("Prediction:")
    st.write(f"The predicted spending score is: {prediction[0]:.2f}")


# ... [Your visualization and model summary code from the original notebook, adjusted for Streamlit] ...

# Model evaluation metrics
st.subheader("Model Evaluation")

col1, col2 = st.columns(2)
col1.metric("R-squared", f"{r2:.2f}")
col2.metric("Mean Squared Error", f"{mse:.2f}")


st.subheader("Regression Summary")
st.text(model_sm.summary())  # Display the summary



# ...[Rest of your code (visualization,etc.)]...

